### ISSUE TITLE
Vulnerability Disclosure

### ISSUE THREAD

**Issue by Idan-D** [jpmckinney/copy_paste_pdf#2]
Hey James 👋🏽

I'm Idan from Snyk Security Team. We track, triage, and verify issues and vulnerabilities within open-source dependencies and work with maintainers to make open-source secure. More information regarding our tracked vulnerabilities can be found [here](https://snyk.io/vuln)

I would like to share with you a vulnerability disclosure privately, I was trying to reach in many ways without success.
How can I contact you privately and share with you the vulnerability disclosure?

Many thanks,
Idan

**Comment by Idan-D** [comment]
Hey @jpmckinney 
Is there any update?

Thanks,
Idan

**Comment by jpmckinney** [comment]
@Idan-D Sorry, my notifications on this repo were misconfigured. Sure, you can reach me at jamespetermckinney (GMail).
